apiVersion: v1
kind: Template
metadata:
  name: selenium-node-chrome
  labels:
    app: selenium
  annotations:
    description: "Selenium Node with Google Chrome browser"
    iconClass: "icon-other-linux"
    tags: "selenium,node,chrome"
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: selenium-node-chrome
    labels:
      app: selenium
  spec:
    replicas: 1
    selector:
      app: selenium
    template:
      metadata:
        name: selenium-node-chrome
        labels:
          app: selenium
      spec:
        containers:
        - env:
          - name: JAVA_OPTS
            value: ${JAVA_OPTS}
          - name: SE_OPTS
            value: ${SE_OPTS}
          - name: HUB_PORT_4444_TCP_ADDR
            value: ${HUB_PORT_4444_TCP_ADDR}
          - name: HUB_PORT_4444_TCP_PORT
            value: ${HUB_PORT_4444_TCP_PORT}
          - name: REMOTE_HOST
            value: ${REMOTE_HOST}
          image: ${IMAGE}
          name: master
          ports:
          - containerPort: 4444
            protocol: TCP
          - containerPort: 5555
            protocol: TCP
- apiVersion: v1
  kind: Service
  metadata:
    name: selenium-node-chrome
    labels:
      app: selenium
  spec:
    type: ClusterIP
    ports:
    - name: node-port
      port: 5555
      targetPort: 5555
      protocol: TCP
    - name: node-port-grid
      port: 4444
      targetPort: 4444
      protocol: TCP
parameters:
  - name: JAVA_OPTS
    description: Options for the Java command
    value: "-Xmx512m -Dselenium.LOGGER.level=WARNING"
  - name: SE_OPTS
    description: Options for the Node
    value: ""
  - name: HUB_PORT_4444_TCP_ADDR
    description: The Hub to connect to
    value: "selenium-hub"
  - name: HUB_PORT_4444_TCP_PORT
    description: The Hub port to connect to
    value: "4444"
  - name: REMOTE_HOST
    description: The remote host
    value: ""
  - name: NODE_ID
    description: Unique ID assigned to the node
    generate: expression
    from: '[a-z]{4}'
  - name: IMAGE
    description: Target image